version: '3.7'

services:
  api:
    volumes:
      - .:/usr/src/app
    ports: 
      - "${PORT:-8080}:8080"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - GEOBASE_HOST
      - TRIPLESTORE_CACHE_URL 
      - TRIPLESTORE_CACHE_PORT
      - GEOM_DATA_SVC_ENDPOINT
      - LOCI_DATATYPES_STATIC_JSON
      - GEOBASE_URL
      - PG_HOST
      - PG_PORT
      - PG_DB_NAME
      - PG_USER
      - PG_PASSWORD
      - PG_TABLE
