version: '3.7'

services:
  api:
    volumes:
      - .:/usr/src/app
    ports: 
      - 8080
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - GEOBASE_HOST
      - TRIPLESTORE_CACHE_URL 
      - GEOBASE_URL
      - PG_HOST
      - PG_PORT
      - PG_DB_NAME
      - PG_USER
      - PG_PASSWORD
