version: '3.7'

services:
  api:
    build: 
      context: .
      target: base
    ports: 
      - 8080
    restart: always
  caddy:
    image: abiosoft/caddy
    ports:
      - 443:2015
    environment:
      - ACME_AGREE=true
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./certs:/etc/ssl
    links:
      - api
    restart: always
